title: Emmanuella Cann
description: Psychology and Data Science Student University of Virginia
![IMG_2634 (1)](https://github.com/Cann-Emma/portfolio/assets/143144256/c62e16ae-3fe2-488b-81bf-240944118b96)
show_downloads: True
theme: jekyll-theme-minimal
