title: Emmanuella Cann
![images](https://github.com/Cann-Emma/portfolio/assets/143144256/f4dc6b8f-1b43-4763-a0a2-389c0df6d96a)
description: Psychology and Data Science Student University of Virginia
![IMG_2634 (1)](https://github.com/Cann-Emma/portfolio/assets/143144256/39be28de-c3f5-4c0d-8864-bbae2dbf5772)

show_downloads: True
theme: jekyll-theme-minimal
